baseurl = "https://example.org"
title = "Universal"
theme = "universal"
themesDir = "themes"
languageCode = "en-us"
defaultContentLanguage = "en"
disqusShortname = "devcows"
googleAnalytics = ""
paginate = 10
baseURL = ""
publishDir = "public"

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 2

[[menu.main]]
identifier = "faq"
name = "FAQ"
url = "/faq/"
weight = 3

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 4

[[menu.topbar]]
weight = 1
name = "GitHub"
url = "https://github.com/devcows/hugo-universal-theme"
pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
weight = 2
name = "Facebook"
url = "http://facebook.com"
pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
weight = 3
name = "Twitter"
url = "http://twitter.com"
pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
weight = 4
name = "Email"
url = "mailto:your@email.com"
pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
viewMorePostLink = "/blog/"
author = "DevCows"
defaultKeywords = [ "devows", "hugo", "go" ]
mainSections = [ "blog" ]
defaultDescription = "Site template made by devcows using hugo"
facebook_site = ""
twitter_site = "GoHugoIO"
default_sharing_image = "img/sharing-default.png"
enableGoogleMaps = true
googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"
latitude = "-12.043333"
longitude = "-77.028333"
style = "default"
formspree_action = "https://formspree.io/sample/of/endpoint"
contact_form_ajax = false
about_us = "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>"
copyright = "Copyright (c) 2015 - 2016, YourCompany; all rights reserved."
date_format = "January 2, 2006"
logo = "img/logo.png"
logo_small = "img/logo-small.png"
address = """
<p class="text-uppercase"><strong>Universal Ltd.</strong>
        <br>13/25 New Avenue
        <br>Newtown upon River
        <br>45Y 73J
        <br>England
        <br>
        <strong>Great Britain</strong>
      </p>
      """

  [params.topbar]
  enable =false
  text = """
<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

  [params.widgets]
  categories = true
  tags = true
  search = true

  [params.carousel]
  enable = true

  [params.features]
  enable = true

  [params.testimonials]
  enable = true
  title = "Testimonials"
  subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

  [params.see_more]
  enable = true
  icon = "far fa-file-alt"
  title = "Do you want to see more?"
  subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
  link_url = "#"
  link_text = "Check other homepages"

  [params.clients]
  enable = true
  title = "Our Clients"
  subtitle = ""

  [params.recent_posts]
  enable = true
  title = "From our blog"
  subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."

[permalinks]
blog = "/blog/:year/:month/:day/:filename/"
